# Generated by Django 5.1.1 on 2024-09-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_delete_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='is_occupied',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='court',
            name='time_of_occupation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
