# Generated by Django 5.1.1 on 2024-09-17 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_delete_reservation'),
        ('members', '0007_delete_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='courts.court'),
        ),
    ]
